nested_list = ['Raghul','Kumar',[536,7367],[True,False]]
print(nested_list[0])
print(nested_list[1])
print(nested_list[2])
print(nested_list[2][0])
print(nested_list[2][1])
print(nested_list[2][0:2])
print(nested_list[3])
print(nested_list[3][0])
print(nested_list[3][1])

nested_list=('Raghul','Kumar',[22,23],[True,False])
print(nested_list[0][0])
print(nested_list[0][1])
print(nested_list[1][0])
print(nested_list[1][1])
print(nested_list[2][0])
print(nested_list[2][1])
print(nested_list[2][0:1])